---
title: "R Notebook"
---
```{r}

# class activity
CustomerData <- read.csv("~/code/data-science/data-preprocessing-math2349/data/CustomerData.csv")
   head(CustomerData)

   is.na(CustomerData)
   
# Task 1: Identify the location(s) of missing value(s) for JobCategory
  which(is.na("CustomerData$JobCategory"))

# Task 2: Find the total number of missing values in JobCategory

  is.na(CustomerData$JobCategory)
  
# Task 3: Find the total number of missing values in the whole data set

  sum(is.na(CustomerData))

# Task 4: Find the total number of missing values in each column (variable) in the data set
   
  colSums(is.na(CustomerData))

```


```{r}  
  
# slide 20
  
  df <- data.frame(col1 = c(1:3, NA),
                 col2 = c("credit", "","cash", "amex"), 
                 col3 = c(TRUE, FALSE, TRUE, TRUE), 
                 col4 = c(2.5, 4.2, 3.2, NA),
                 stringsAsFactors = FALSE)

# Task 1: Find the total number of missing values in each column.

  colSums(is.na(df))  
    
# Task 2: Assume that empty string in col2 represents a missing value, so replace it with a NA

  df$col2[which(df$col2 == "NULL")] <- NA

# Task 3: Now, identify the location(s) of missing value(s) for col2
  

    is.na(df$col2)


## ~old_todo~ question goes here    
mean(df$col4, na.rm = TRUE)

mean(na.omit(df$col4))

mean( df$col4[ complete.cases(df$col4) ] )
  
  
# from: http://rare-phoenix-161610.appspot.com/secured/demos/Week_06_Demo.html#25
  
df_listwise <- data.frame(col1 = c(1:3, NA),
                 col2 = c("this", NA,"is", "text"), 
                 col3 = c(TRUE, FALSE, TRUE, TRUE), 
                 col4 = c(2.5, 4.2, 3.2, NA),
                 stringsAsFactors = FALSE)

# Calculate mean of col4 using [listwise deletion](https://en.wikipedia.org/wiki/Listwise_deletion) of missing values (i.e. if one observation is missing in any column, do not include it while computing mean)

df_listwise[[1]]

for (i in 1:length(df_listwise$col1)) {
  df_listwise[[i]][which(df_listwise[[i]] == "NULL")]
}




```
[listwise deletion]: https://en.wikipedia.org/wiki/Listwise_deletion


```{r}
#install.packages("Hmisc")
library(Hmisc)

x <- data.frame( no = c(1:6),
                 x1 = c(15000 , 20000, 23000, NA, 18000, 21000), 
                 x2 = c(4, NA, 4, 5, 7, 8),
                 x3 = factor(c(NA, "False", "False", "False", "True", "True"))
                 )

x1 <- 
  impute(x$x1, fun = mean) %>% 
  print()


weight_height_NA <- read.csv("~/code/data-science/data-preprocessing-math2349/data/weight_height_NA.csv")
head(weight_height_NA)

recoded <- weight_height_NA$weight[which(weight_height_NA$weight == "-")] <- NA

sum(is.na(weight_height_NA$weight))

impute(weight_height_NA$weight, fun = mean) %>%
  head()


df <- data.frame(col1 = c( 2, 0/0, NA, 1/0, -Inf, Inf),
                 col2 = c( NA, Inf/0, 2/0, NaN, -Inf, 4)
                )

df[1]

is.finite(df[1])



for (i in 1:length(df)) {
  is.finite(df[[i]]) %>%
  print()
}

```

